name: Qemu-gunyah release v2
run-name: Qemu-gunyah release v2
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  apiLevel: 35
  ndkPath: "$HOME/android-ndk-r30-beta1"
  toolchain: "$HOME/android-ndk-r30-beta1/toolchains/llvm/prebuilt/linux-x86_64"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code   
      uses: actions/checkout@v6
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - name: 部署
      run: |
        sudo apt update
        sudo apt install -y build-essential ninja-build pkg-config xz-utils device-tree-compiler
        sudo pip3 install --upgrade meson
        wget https://dl.google.com/android/repository/android-ndk-r30-beta1-linux.zip -O ndk.zip
        unzip -q ndk.zip -d $HOME
        wget https://raw.githubusercontent.com/AnyLaySys/qemu-gunyah-build/main/1.sh
        chmod +x ./1.sh
        ./1.sh
      
    - name: build
      run: |
        chmod +x ./3.sh
        ./3.sh
     
    - name: Zip the Build
      run: zip -r ${{ secrets.ReleaseZipName }} .

    - name: 上传
      uses: actions/upload-artifact@v7
      with:
        name: qemu-gunyah
        path: ${{ secrets.ReleaseZipName }}
        archive: false
        if-no-files-found: error
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          ${{ secrets.ReleaseZipName }}.zip
          LICENSE 
